"""Add priority to tasks and github_connected to users

Revision ID: 3c8d9e2f1a4b
Revises: d8b7f3a2c1e4
Create Date: 2026-05-06 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c8d9e2f1a4b'
down_revision = 'd8b7f3a2c1e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('priority', sa.String(length=20), nullable=True, server_default='medium'))
    op.add_column('users', sa.Column('github_connected', sa.Boolean(), nullable=True, server_default='false'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'github_connected')
    op.drop_column('tasks', 'priority')
    # ### end Alembic commands ###
