"""Add audit logs and system settings

Revision ID: 93a1f8b3c4d5
Revises: e2f4g5h6i7j8
Create Date: 2026-05-07 00:39:00.000000

"""
from alembic import op
import sqlalchemy as sa
import json
from datetime import datetime, timezone

# revision identifiers, used by Alembic.
revision = '93a1f8b3c4d5'
down_revision = 'e2f4g5h6i7j8'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('actor_user_id', sa.Integer(), nullable=True),
        sa.Column('actor_role', sa.String(length=20), nullable=True),
        sa.Column('action', sa.String(length=100), nullable=False),
        sa.Column('resource_type', sa.String(length=50), nullable=True),
        sa.Column('resource_id', sa.String(length=50), nullable=True),
        sa.Column('ip', sa.String(length=45), nullable=True),
        sa.Column('user_agent', sa.String(length=255), nullable=True),
        sa.Column('metadata_info', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_logs_actor_time', 'audit_logs', ['actor_user_id', 'created_at'], unique=False)
    op.create_index('idx_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.create_index('idx_audit_logs_resource', 'audit_logs', ['resource_type'], unique=False)

    system_settings_table = op.create_table('system_settings',
        sa.Column('key', sa.String(length=100), nullable=False),
        sa.Column('value', sa.JSON(), nullable=False),
        sa.Column('updated_by', sa.Integer(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
        sa.PrimaryKeyConstraint('key')
    )
    
    bind = op.get_bind()
    if bind.dialect.name == 'postgresql':
        op.create_check_constraint(
            'check_valid_role',
            'users',
            "role IN ('developer', 'team_lead', 'admin')"
        )
    
    # Seed default system settings
    op.bulk_insert(
        system_settings_table,
        [
            {
                'key': 'app_name',
                'value': 'DevSync',
                'updated_at': datetime.now(timezone.utc)
            },
            {
                'key': 'allow_registration',
                'value': True,
                'updated_at': datetime.now(timezone.utc)
            },
            {
                'key': 'default_user_role',
                'value': 'developer',
                'updated_at': datetime.now(timezone.utc)
            },
            {
                'key': 'github_integration_enabled',
                'value': True,
                'updated_at': datetime.now(timezone.utc)
            },
            {
                'key': 'notification_settings',
                'value': {
                    'email_notifications': True,
                    'task_assignments': True,
                    'project_updates': True
                },
                'updated_at': datetime.now(timezone.utc)
            }
        ]
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    if bind.dialect.name == 'postgresql':
        op.drop_constraint('check_valid_role', 'users', type_='check')

    op.drop_table('system_settings')
    
    op.drop_index('idx_audit_logs_resource', table_name='audit_logs')
    op.drop_index('idx_audit_logs_action', table_name='audit_logs')
    op.drop_index('idx_audit_logs_actor_time', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
