"""Add reports table for storing generated reports

Revision ID: e2f4g5h6i7j8
Revises: 3c8d9e2f1a4b
Create Date: 2026-05-06 15:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2f4g5h6i7j8'
down_revision = '3c8d9e2f1a4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('date_range', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reports_generated_at', 'reports', ['generated_at'], unique=False)
    op.create_index('idx_reports_type', 'reports', ['report_type'], unique=False)
    op.create_index('idx_reports_user_generated', 'reports', ['user_id', 'generated_at'], unique=False)
    op.create_index('idx_reports_user_id', 'reports', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_reports_user_id', table_name='reports')
    op.drop_index('idx_reports_user_generated', table_name='reports')
    op.drop_index('idx_reports_type', table_name='reports')
    op.drop_index('idx_reports_generated_at', table_name='reports')
    op.drop_table('reports')
    # ### end Alembic commands ###
